### ISSUE TITLE
"DSSE Multi-signature Verification" protocol lacks detail about threshold verification

### ISSUE THREAD

**Issue by lukpueh** [secure-systems-lab/dsse#51]
The [protocol](https://github.com/secure-systems-lab/dsse/blob/469c6e9fa6c4b7252fb71101084561cfc4cd0fa5/protocol.md#multi-signature-verification) implies that threshold verification is performed in-band:

```
For each (SIGNATURE, KEYID) in SIGNATURES,
  ...
  Verify SIGNATURE ...
  ...

Reject if the cardinality of ACCEPTED_KEYS is less than t[hreshold].
```

However, it does not describe how to prevent counting multiple signatures from the same private key towards the threshold. It can be prevented by:
1. checking for distinct signatures, which limits DSSE to deterministic signing algorithms and requires non-ambiguous signature data, or by
2. checking that no public key is re-used to successfully verify multiple signatures

I suggest to integrate (2) in the protocol, and optionally emphasize that the keys passed to the verification routine need to be distinct in order to not count multiple signatures from the same private key towards the threshold.

**Comment by MarkLodato** [comment]
Sent out #52 as a possible suggestion to replace "cardinality of" with "unique keys in". I suspect that will avoid any ambiguity?
