### ISSUE TITLE
Have you considered signing a hash digest of the payload instead of the payload itself?

### ISSUE THREAD

**Issue by jsmith97** [secure-systems-lab/dsse#53]
Hi,

I am looking to implement this standard internally and it would appear to me that cryptographically signing a hash digest of the payload would be less compute intensive and allow the use of services such as AWS KMS that has a 4096 byte limit on the size of data you can directly sign (https://docs.aws.amazon.com/cli/latest/reference/kms/sign.html). I would be happy to create reference implementation in python and PR it into the project but it would require the envelope to be changed to something like

{
  "payload": "<Base64(SERIALIZED_BODY)>",
  "payloadType": "<PAYLOAD_TYPE>",
  "signatures": [{
    "keyid": "<KEYID>",
    "hashAlgorithms": "sha256",
    "sig": "<Base64(SIGNATURE)>"
  }]
}

or agreement on one hash algorithm that should always be used.

Thanks

Ben

**Comment by TomHennen** [comment]
@MarkLodato WDYT?

**Comment by TomHennen** [comment]
One thing to note is that ["Sign() is an arbitrary digital signature format. Details are agreed upon out-of-band by the signer and verifier. This specification places no restriction on the signature algorithm or format."](https://github.com/secure-systems-lab/dsse/blob/master/protocol.md#:~:text=Sign()%20is%20an%20arbitrary%20digital%20signature%20format.%20Details%20are%20agreed%20upon%20out%2Dof%2Dband%20by%20the%20signer%20and%20verifier.%20This%20specification%20places%20no%20restriction%20on%20the%20signature%20algorithm%20or%20format.) so there's no reason you couldn't do this.

Also note that the reference implementation that uses ecdsa [does seem to hash the payload before signing](https://github.com/secure-systems-lab/dsse/blob/master/implementation/ecdsa.py#L28).

Does that help you out or could I be misunderstanding something?

**Comment by jsmith97** [comment]
Thanks @TomHennen for the quick response, it wasn't obvious to me that it was acceptable to do this. That answers my question.
